### ISSUE TITLE
QA - Week 9 todo

### ISSUE THREAD

**Issue by Living-Neutral** [BronCAD/BronCAD#5]
- [ ] Look into documentation styles for C#
- [ ] Look up github wiki and see how it works
- [ ]  Study Markdown
- [ ] Study Unit tests
